[package]
name = "projfetch"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
crossterm = "0.28.1"
human-repr = "1.1.0"
ignore = "0.4.22"
itertools = "0.13.0"
termcolor = "1.4.1"
